### ISSUE TITLE
Unable to run in Windows

### ISSUE THREAD

**Issue by kristopher-wood** [online-ml/chantilly#21]
Hello all,

I'm running Python 3.9 in an Anaconda environment on Windows.

After following the installation instructions, I get the following on the command line:

```
Python 3.9.6 (default, Jul 30 2021, 11:42:22) [MSC v.1916 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.22.0 -- An enhanced Interactive Python.

In [1]: chantilly run
  File "<ipython-input-1-c90d62525bcd>", line 1
    chantilly run
              ^
SyntaxError: invalid syntax
```

Are there additional steps needed to get it running in Windows?

**Comment by raphaelsty** [comment]
Hi @kristopher-wood, chantilly run is a command line, you should execute it from your terminal and not from your python interpreter 🙂

**Comment by kristopher-wood** [comment]
Ah ok! That makes sense, but when I run it from the windows command line I get command not found.

**Comment by raphaelsty** [comment]
I think your terminal doesn't make the connection with your Python environment. Are you using Anaconda or Miniconda? If so, think about activating the environment on which you installed chantilly 🙂

**Comment by kristopher-wood** [comment]
I was using the power shell terminal launched from anaconda navigator for the environment I'd installed Chantilly in. I guess that launcher doesn't actually open the terminal in the same environment.

**Comment by kristopher-wood** [comment]
I got it to run in Windows! The solution was as follows:

1. Install Ubuntu for Windows via the Windows Marketplace
2. From the Ubuntu terminal, install Anaconda
3. Restart the Ubuntu terminal and run `apt-get -y install build-essential`
4. pip install chantilly
5. chantilly run

Success!
