### ISSUE TITLE
'Unsupported operand type' error prediction in README example

### ISSUE THREAD

**Issue by arisliang** [online-ml/chantilly#23]
For `Making a prediction` part of the README,

`r.json()` contains this error:

>{'message': 'TypeError("unsupported operand type(s) for -: \'str\' and \'float\'")'}

![image](https://user-images.githubusercontent.com/1115503/149933845-9f156c37-50b4-41e5-852d-033a8dc82c0c.png)

river and chantilly version:
('0.9.0', '0.3.0')

**Comment by MaxHalford** [comment]
Hey! That example isn't supposed to work. It's just for the sake example and isn't tested or anything :)
